# Generated by Django 3.1.2 on 2020-10-09 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchedRecip',
        ),
        migrations.AddField(
            model_name='recipient',
            name='email_address',
            field=models.EmailField(default='dummy@placeholder.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='frequency',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recipients',
            field=models.ManyToManyField(to='schedules.Recipient'),
        ),
    ]
