# Generated by Django 3.1.2 on 2020-10-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20201009_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('content', 'frequency')},
        ),
    ]
