# Generated by Django 3.1.2 on 2020-10-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20201010_0949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('content', 'frequency', 'start_date', 'end_date')},
        ),
    ]
