# Generated by Django 3.1.2 on 2020-10-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20201010_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
