# Generated by Django 3.1.2 on 2020-10-25 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20201020_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email_address',
            field=models.EmailField(default='dummy@placeholder.com', max_length=254, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('description', 'content', 'frequency', 'start_date', 'end_date')},
        ),
    ]
