# Generated by Django 3.1.2 on 2020-11-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_auto_20201025_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('description', 'subject', 'content', 'frequency', 'start_date', 'end_date')},
        ),
    ]
