# Generated by Django 3.1.2 on 2020-11-04 13:26

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_auto_20201103_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('IN', 'Not Scheduled'), ('CO', 'Completed')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(default=utils.models.default_end_date),
        ),
    ]
