# Generated by Django 3.1.2 on 2020-11-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_auto_20201104_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('NA', 'Not Added to Celery Beat'), ('CO', 'Completed'), ('PA', 'Paused')], default='NA', max_length=2),
        ),
    ]
