# Generated by Django 3.1.2 on 2020-11-05 08:18

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_auto_20201104_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(default=utils.models.default_end_date),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(default=utils.models.default_start_date),
        ),
    ]
