# Generated by Django 3.1.2 on 2020-11-06 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_auto_20201105_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DurationField(default=datetime.timedelta(0), unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
