# Generated by Django 3.1.2 on 2020-11-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_scheduleinterval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleInterval',
            new_name='Interval',
        ),
    ]
