# Generated by Django 3.1.2 on 2020-11-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0016_auto_20201106_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interval',
            new_name='ScheduleInterval',
        ),
    ]
