# Generated by Django 3.1.2 on 2020-11-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0017_auto_20201117_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleInterval',
            new_name='Interval',
        ),
    ]
